spring:
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.123.130:3306/service?characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: schoolsell_2020
server:
  servlet:
    context-path: /service
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  port: 8200

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml

filePath: D:/images/upload/