spring:
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service?characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: schoolsell_2020
server:
  servlet:
    context-path: /service
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  port: 8200
  ssl:
    # SSL 证书路径，classpath 必不可少
    key-store: classpath:4754508.jks
    # SSL 证书密码
    key-store-password: V90HOvS6
    # 证书类型
    key-store-type: JKS
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml

